const LANG_KEY = "ps_lang_v1";
const SUP_LANGS = [
    { code: "pl", label: "Polski", short: "PL" },
    { code: "en", label: "English", short: "EN" }
];

let CURRENT_LANG = localStorage.getItem(LANG_KEY) || "pl";

// Повний список пар
const PAIRS_DATA = [
    { name: "GBP/USD OTC", market: "OTC" }, { name: "USD/CAD OTC", market: "OTC" },
    { name: "EUR/GBP OTC", market: "OTC" }, { name: "EUR/JPY OTC", market: "OTC" },
    { name: "GBP/JPY OTC", market: "OTC" }, { name: "AUD/NZD OTC", market: "OTC" },
    { name: "USD/RUB OTC", market: "OTC" }, { name: "CAD/JPY OTC", market: "OTC" },
    { name: "EUR/USD", market: "REAL" }, { name: "BTC/USD", market: "CRYPTO" },
    { name: "ETH/USD", market: "CRYPTO" }, { name: "XAU/USD", market: "COMMOD" },
    { name: "AAPL/USD", market: "STOCKS" }, { name: "AMZN/USD", market: "STOCKS" }
];

const I18N = {
    pl: {
        app_title: "Signal AI Pro", hero_title: "Handluj z AI", hero_sub: "Inteligentne sygnały dla zyskownego handlu",
        header_become_vip: "Zostań VIP", field_pair_label: "Para walutowa", field_pair_ph: "Wybierz parę",
        field_expiry_label: "Czas wygaśnięcia", field_expiry_ph: "Wybierz czas", field_model_label: "Model AI",
        btn_get_signal: "Pobierz sygnał", signal_title: "Sygnał", dir_buy: "GÓRA", dir_sell: "DÓŁ",
        k_conf: "PEWNOŚĆ", k_acc: "DOKŁADNOŚĆ", k_market: "RYNEK", k_strength: "SIŁA", k_vol: "WOLUMEN",
        k_time: "CZAS", k_valid: "WAŻNE DO", v_strength_high: "Wysoka", v_vol_med: "Średni",
        faq_title: "FAQ", cp_search_ph: "Szukaj pary...", btn_repeat: "Powtórz", btn_reset: "Resetuj",
        faqs: [
            { q: "Co to jest sygnał AI?", a: "To prognoza wygenerowana przez algorytmy sieci neuronowych." },
            { q: "Czy to jest darmowe?", a: "Tak, dostęp dla naszych partnerów jest całkowicie bezpłatny." }
        ]
    },
    en: {
        app_title: "Signal AI Pro", hero_title: "Trade with AI", hero_sub: "Smart signals for profitable trading",
        header_become_vip: "Become VIP", field_pair_label: "Currency Pair", field_pair_ph: "Select pair",
        field_expiry_label: "Expiry Time", field_expiry_ph: "Select time", field_model_label: "AI Model",
        btn_get_signal: "Get Signal", signal_title: "Signal", dir_buy: "CALL", dir_sell: "PUT",
        k_conf: "CONFIDENCE", k_acc: "ACCURACY", k_market: "MARKET", k_strength: "STRENGTH", k_vol: "VOLUME",
        k_time: "TIME", k_valid: "VALID UNTIL", v_strength_high: "Strong", v_vol_med: "Medium",
        faq_title: "FAQ", cp_search_ph: "Search pair...", btn_repeat: "Repeat", btn_reset: "Reset",
        faqs: [
            { q: "What is an AI signal?", a: "It is a forecast generated by neural network algorithms." },
            { q: "Is it free?", a: "Yes, access for our partners is completely free." }
        ]
    }
};

function t(key) { return I18N[CURRENT_LANG][key] || I18N["en"][key] || ""; }

function applyI18n() {
    document.getElementById("vipText").textContent = t("header_become_vip");
    document.querySelector(".main-heading h1").textContent = t("hero_title");
    document.querySelector(".main-heading p").textContent = t("hero_sub");
    document.getElementById("getSignalBtn").textContent = t("btn_get_signal");
    document.getElementById("pairField").placeholder = t("field_pair_ph");
    document.getElementById("timeField").placeholder = t("field_expiry_ph");
    document.getElementById("cpSearch").placeholder = t("cp_search_ph");
    const labels = document.querySelectorAll(".field-block label");
    labels[0].textContent = t("field_pair_label");
    labels[1].textContent = t("field_expiry_label");
    labels[2].textContent = t("field_model_label");
    document.querySelector(".signal-title span").textContent = t("signal_title");
    document.getElementById("langCode").textContent = CURRENT_LANG.toUpperCase();
    document.getElementById("langFlag").src = `images/flags/${CURRENT_LANG}.svg`;
    renderFAQ();
    renderLangMenu();
}

function renderFAQ() {
    const container = document.getElementById("faqContent");
    if (!container) return;
    container.innerHTML = I18N[CURRENT_LANG].faqs.map(item => `
        <div class="faq-item">
            <button class="faq-question" onclick="this.parentElement.classList.toggle('open')">
                <span>${item.q}</span>
                <svg class="faq-icon" width="12" height="8" viewBox="0 0 12 8"><path d="M1 1l5 5 5-5" stroke="white" fill="none" stroke-width="2"/></svg>
            </button>
            <div class="faq-answer">${item.a}</div>
        </div>
    `).join("");
}

function renderLangMenu() {
    const menu = document.getElementById("langMenu");
    menu.innerHTML = SUP_LANGS.map(l => `<li onclick="setLang('${l.code}')"><img class="lang-flag" src="images/flags/${l.code}.svg"> ${l.label}</li>`).join("");
}

window.setLang = (code) => { CURRENT_LANG = code; localStorage.setItem(LANG_KEY, code); applyI18n(); document.getElementById("langMenu").classList.remove("open"); };
document.getElementById("langBtn").onclick = (e) => { e.stopPropagation(); document.getElementById("langMenu").classList.toggle("open"); };

// =============================
// ПОПАПИ (ЗАКРИТТЯ ТА ПОШУК)
// =============================

window.selectField = (type) => {
    if (type === 'pair') {
        document.getElementById("cpPopup").setAttribute("aria-hidden", "false");
        renderPairs(PAIRS_DATA);
    } else {
        document.getElementById("exPopup").setAttribute("aria-hidden", "false");
        renderExpiry();
    }
};

// Закриття при кліку на темний фон
document.querySelectorAll('.cp-overlay, .ex-overlay').forEach(overlay => {
    overlay.onclick = function(e) {
        if (e.target === this) closePopups();
    };
});

function closePopups() {
    document.getElementById("cpPopup").setAttribute("aria-hidden","true");
    document.getElementById("exPopup").setAttribute("aria-hidden","true");
    document.getElementById("cpSearch").value = ""; 
}

// ЛОГІКА ПОШУКУ
document.getElementById("cpSearch").oninput = function() {
    const query = this.value.toLowerCase();
    const filtered = PAIRS_DATA.filter(p => p.name.toLowerCase().includes(query));
    renderPairs(filtered);
};

function renderPairs(data) {
    const list = document.getElementById("cpList");
    list.innerHTML = data.map(p => `
        <div class="cp-item" onclick="setPair('${p.name}')">
            <span>${p.name}</span>
            <small>${p.market}</small>
        </div>
    `).join("");
}

// ЧАС ЯК НА СКРІНШОТІ
function renderExpiry() {
    const grid = document.getElementById("exGrid");
    const times = ["S3", "S15", "S30", "M1", "M3", "M5", "M30", "H1", "H4"];
    grid.innerHTML = times.map(t => `<button class="ex-chip" onclick="setExpiry('${t}')">${t}</button>`).join("");
}

window.setPair = (val) => { document.getElementById("pairField").value = val; closePopups(); checkReady(); };
window.setExpiry = (val) => { document.getElementById("timeField").value = val; closePopups(); checkReady(); };

function checkReady() {
    const btn = document.getElementById("getSignalBtn");
    if (document.getElementById("pairField").value && document.getElementById("timeField").value) {
        btn.disabled = false; btn.classList.add("active");
    }
}

// =============================
// СИГНАЛИ ТА ЦЕНТРУВАННЯ
// =============================

document.getElementById("getSignalBtn").onclick = startAnalysis;
document.getElementById("sigRepeat").onclick = startAnalysis;
document.getElementById("sigReset").onclick = () => location.reload();

function startAnalysis() {
    document.getElementById("getSignalBtn").disabled = true;
    const progress = document.getElementById("sigProgress");
    const loader = document.querySelector(".wave-loader");
    const analysisBox = document.getElementById("sigAnalysis");
    const resultBox = document.getElementById("sigResult");

    resultBox.hidden = true;
    analysisBox.style.display = "block";
    
    // Фіксація центрування іконки
    if (loader) {
        loader.style.display = "block";
        loader.style.margin = "0 auto 20px auto"; 
    }

    let p = 0;
    const interval = setInterval(() => {
        p += 5;
        progress.style.width = p + "%";
        if (p >= 100) {
            clearInterval(interval);
            if (loader) loader.style.display = "none";
            analysisBox.style.display = "none";
            showResult();
        }
    }, 100);
}

function showResult() {
    const res = document.getElementById("sigResult");
    res.hidden = false;
    const isBuy = Math.random() > 0.5;
    const pair = document.getElementById("pairField").value;

    document.getElementById("sigDirection").textContent = isBuy ? t("dir_buy") : t("dir_sell");
    document.getElementById("sigDirection").className = `rg2-ribbon ${isBuy ? 'buy' : 'sell'}`;
    document.getElementById("sigPair").textContent = pair;
    
    document.getElementById("sigConf").textContent = Math.floor(Math.random() * 10 + 85) + "%";
    document.getElementById("sigAcc").textContent = Math.floor(Math.random() * 5 + 93) + "%";

    const listRows = document.querySelectorAll(".rg2-list .row");
    listRows[0].querySelector(".v").textContent = pair.includes("OTC") ? "OTC" : "REAL";
    listRows[1].querySelector(".v").textContent = t("v_strength_high");
    listRows[2].querySelector(".v").textContent = t("v_vol_med");

    const now = new Date();
    document.getElementById("sigTime").textContent = now.getHours().toString().padStart(2, '0') + ":" + now.getMinutes().toString().padStart(2, '0');

    const valid = new Date(now.getTime() + 3 * 60000);
    document.getElementById("sigValid").textContent = valid.getHours().toString().padStart(2, '0') + ":" + valid.getMinutes().toString().padStart(2, '0');

    document.getElementById("sigRepeat").textContent = t("btn_repeat");
    document.getElementById("sigReset").textContent = t("btn_reset");
}

document.onclick = () => {
    const langMenu = document.getElementById("langMenu");
    if(langMenu) langMenu.classList.remove("open");
};

document.addEventListener("DOMContentLoaded", applyI18n);