// =============================
// Конфігурація та Дані
// =============================
const LANG_KEY = "ps_lang_v1";
const SUP_LANGS = [
    { code: "pl", label: "Polski", short: "PL" },
    { code: "en", label: "English", short: "EN" }
];

let CURRENT_LANG = localStorage.getItem(LANG_KEY) || "pl";

const PAIRS_DATA = [
    { name: "GBP/USD OTC", market: "OTC" }, { name: "USD/CAD OTC", market: "OTC" },
    { name: "EUR/GBP OTC", market: "OTC" }, { name: "EUR/JPY OTC", market: "OTC" },
    { name: "GBP/JPY OTC", market: "OTC" }, { name: "AUD/NZD OTC", market: "OTC" },
    { name: "EUR/USD", market: "REAL" }, { name: "BTC/USD", market: "CRYPTO" },
    { name: "ETH/USD", market: "CRYPTO" }, { name: "XAU/USD", market: "COMMOD" }
];

const I18N = {
    pl: {
        app_title: "Signal AI Pro",
        hero_title: "Handluj з AI",
        hero_sub: "Inteligentne sygnały dla zyskownego handlu",
        header_become_vip: "Zostań VIP",
        field_pair_label: "Para walutowa",
        field_pair_ph: "Wybierz parę",
        field_expiry_label: "Czas wygaśnięcia",
        field_expiry_ph: "Wybierz час",
        field_model_label: "Model AI",
        btn_get_signal: "Pobierz sygnał",
        signal_title: "Sygnał",
        dir_buy: "GÓRA",
        dir_sell: "DÓŁ",
        k_conf: "PEWNOŚĆ",
        k_acc: "DOKŁADNOŚĆ",
        k_market: "RYNEK",
        k_strength: "SIŁA",
        k_time: "CZAS",
        k_valid: "WAŻNE DO",
        v_strength_high: "Wysoka",
        faq_title: "Często zadawane pytania (FAQ)",
        faqs: [
            { q: "Co to jest sygnał AI?", a: "To prognoza wygenerowana przez algorytmy sieci neuronowych." },
            { q: "Jak korzystać з bota?", a: "Wybierz parę, czas i otwórz transakcję zgodnie з kierunkiem." },
            { q: "Czy to jest darmowe?", a: "Tak, dostęp dla naszych partnerów jest całkowicie bezpłatny." }
        ]
    },
    en: {
        app_title: "Signal AI Pro",
        hero_title: "Trade with AI",
        hero_sub: "Smart signals for profitable trading",
        header_become_vip: "Become VIP",
        field_pair_label: "Currency Pair",
        field_pair_ph: "Select pair",
        field_expiry_label: "Expiry Time",
        field_expiry_ph: "Select time",
        field_model_label: "AI Model",
        btn_get_signal: "Get Signal",
        signal_title: "Signal",
        dir_buy: "CALL",
        dir_sell: "PUT",
        k_conf: "CONFIDENCE",
        k_acc: "ACCURACY",
        k_market: "MARKET",
        k_strength: "STRENGTH",
        k_time: "TIME",
        k_valid: "VALID UNTIL",
        v_strength_high: "Strong",
        faq_title: "Frequently Asked Questions",
        faqs: [
            { q: "What is an AI signal?", a: "It is a forecast generated by neural network algorithms." },
            { q: "How to use the bot?", a: "Select a pair, timeframe, and open a trade following the direction." },
            { q: "Is it free?", a: "Yes, access for our partners is completely free." }
        ]
    }
};

// =============================
// Основна Логіка (I18n & UI)
// =============================

function t(key) {
    return I18N[CURRENT_LANG][key] || I18N["en"][key] || "";
}

function applyI18n() {
    document.title = t("app_title");
    document.getElementById("vipText").textContent = t("header_become_vip");
    document.querySelector(".main-heading h1").textContent = t("hero_title");
    document.querySelector(".main-heading p").textContent = t("hero_sub");
    document.getElementById("getSignalBtn").textContent = t("btn_get_signal");
    document.getElementById("pairField").placeholder = t("field_pair_ph");
    document.getElementById("timeField").placeholder = t("field_expiry_ph");

    const labels = document.querySelectorAll(".field-block label");
    labels[0].textContent = t("field_pair_label");
    labels[1].textContent = t("field_expiry_label");
    labels[2].textContent = t("field_model_label");

    document.querySelector(".signal-title span").textContent = t("signal_title");
    document.querySelector(".faq-title").textContent = t("faq_title");

    // Оновлення прапора та коду мови
    document.getElementById("langCode").textContent = CURRENT_LANG.toUpperCase();
    document.getElementById("langFlag").src = `images/flags/${CURRENT_LANG}.svg`;

    renderFAQ();
    renderLangMenu();
}

function renderFAQ() {
    const container = document.getElementById("faqContent");
    if (!container) return;
    const items = I18N[CURRENT_LANG].faqs;
    container.innerHTML = items.map(item => `
        <div class="faq-item">
            <button class="faq-question" onclick="this.parentElement.classList.toggle('open')">
                <span>${item.q}</span>
                <svg class="faq-icon" width="12" height="8" viewBox="0 0 12 8"><path d="M1 1l5 5 5-5" stroke="white" fill="none" stroke-width="2"/></svg>
            </button>
            <div class="faq-answer">${item.a}</div>
        </div>
    `).join("");
}

function renderLangMenu() {
    const menu = document.getElementById("langMenu");
    if (!menu) return;
    menu.innerHTML = SUP_LANGS.map(l => `
        <li onclick="setLang('${l.code}')">
            <img class="lang-flag" src="images/flags/${l.code}.svg" alt="">
            <span>${l.label}</span>
        </li>
    `).join("");
}

window.setLang = (code) => {
    CURRENT_LANG = code;
    localStorage.setItem(LANG_KEY, code);
    applyI18n();
    document.getElementById("langMenu").classList.remove("open");
};

document.getElementById("langBtn").onclick = (e) => {
    e.stopPropagation();
    document.getElementById("langMenu").classList.toggle("open");
};

// =============================
// Попапи та Сигнали
// =============================

window.selectField = (type) => {
    if (type === 'pair') {
        document.getElementById("cpPopup").setAttribute("aria-hidden", "false");
        const list = document.getElementById("cpList");
        list.innerHTML = PAIRS_DATA.map(p => `
            <div class="cp-item" onclick="setPair('${p.name}')">
                <span>${p.name}</span>
                <small>${p.market}</small>
            </div>
        `).join("");
    } else {
        document.getElementById("exPopup").setAttribute("aria-hidden", "false");
        const grid = document.getElementById("exGrid");
        const times = ["5s", "15s", "1m", "2m", "5m"];
        grid.innerHTML = times.map(t => `<button class="ex-chip" onclick="setExpiry('${t}')">${t}</button>`).join("");
    }
};

window.setPair = (val) => { document.getElementById("pairField").value = val; closePopups(); checkReady(); };
window.setExpiry = (val) => { document.getElementById("timeField").value = val; closePopups(); checkReady(); };

function closePopups() {
    document.getElementById("cpPopup").setAttribute("aria-hidden", "true");
    document.getElementById("exPopup").setAttribute("aria-hidden", "true");
}

function checkReady() {
    const btn = document.getElementById("getSignalBtn");
    if (document.getElementById("pairField").value && document.getElementById("timeField").value) {
        btn.disabled = false;
        btn.classList.add("active");
    }
}

document.getElementById("getSignalBtn").onclick = function() {
    this.disabled = true;
    const progress = document.getElementById("sigProgress");
    document.getElementById("sigAnalysis").style.display = "block";
    document.getElementById("sigResult").hidden = true;
    
    let p = 0;
    const interval = setInterval(() => {
        p += 5;
        progress.style.width = p + "%";
        if (p >= 100) {
            clearInterval(interval);
            showResult();
        }
    }, 100);
};

function showResult() {
    document.getElementById("sigAnalysis").style.display = "none";
    const res = document.getElementById("sigResult");
    res.hidden = false;

    const isBuy = Math.random() > 0.5;
    document.getElementById("sigDirection").textContent = isBuy ? t("dir_buy") : t("dir_sell");
    document.getElementById("sigDirection").className = `rg2-ribbon ${isBuy ? 'buy' : 'sell'}`;
    document.getElementById("sigPair").textContent = document.getElementById("pairField").value;
    document.getElementById("sigConf").textContent = Math.floor(Math.random() * 15 + 80) + "%";
    document.getElementById("sigAcc").textContent = Math.floor(Math.random() * 5 + 92) + "%";
    
    const now = new Date();
    document.getElementById("sigTime").textContent = now.getHours().toString().padStart(2, '0') + ":" + now.getMinutes().toString().padStart(2, '0');
}

// Закриття меню при кліку будь-де
document.onclick = () => document.getElementById("langMenu").classList.remove("open");

// Ініціалізація
document.addEventListener("DOMContentLoaded", applyI18n);